export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const RESTORE_CHARACTERS = 'RESTORE_CHARACTERS';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
